// ReSharper disable CppClangTidyModernizeMacroToEnum
#ifndef GS_CONFIG_H
#define GS_CONFIG_H

#ifndef HY_VENDOR_ID
  #define HY_VENDOR_ID (0xFFFD)
#endif

#ifndef HY_BUILD_AS_KMDOD
  #define HY_BUILD_AS_KMDOD (0)
#endif

#ifndef HY_KMDOD_ENABLE_VSYNC_INTERRUPTS
  #define HY_KMDOD_ENABLE_VSYNC_INTERRUPTS (1)
#endif

#ifndef GS_ENABLE_ENTRYPOINT_TRACING
  #define GS_ENABLE_ENTRYPOINT_TRACING (1 && DEBUG)
#endif

#define GS_DXGKDDI_IV_VISTA      0x1052
#define GS_DXGKDDI_IV_VISTA_SP1  0x1053
#define GS_DXGKDDI_IV_WIN7       0x2005
#define GS_DXGKDDI_IV_WIN8       0x300E
#define GS_DXGKDDI_IV_WDDM1_3    0x4002
#define GS_DXGKDDI_IV_WDDM1_3_PATH_INDEPENDENT_ROTATION  0x4003
#define GS_DXGKDDI_IV_WDDM2_0    0x5023
#define GS_DXGKDDI_IV_WDDM2_1    0x6003
#define GS_DXGKDDI_IV_WDDM2_1_5  0x6010     // Used in RS1.7 for GPU-P
#define GS_DXGKDDI_IV_WDDM2_1_6  0x6011     // Used in RS1.8 for GPU-P
#define GS_DXGKDDI_IV_WDDM2_2    0x700A
#define GS_DXGKDDI_IV_WDDM2_3    0x8001
#define GS_DXGKDDI_IV_WDDM2_4    0x9006
#define GS_DXGKDDI_IV_WDDM2_5    0xA00B
#define GS_DXGKDDI_IV_WDDM2_6    0xB004
#define GS_DXGKDDI_IV_WDDM2_7    0xC004
#define GS_DXGKDDI_IV_WDDM2_8    0xD001
#define GS_DXGKDDI_IV_WDDM2_9    0xE003
#define GS_DXGKDDI_IV_WDDM3_0    0xF003

#ifndef DXGKDDI_INTERFACE_VERSION
  #if HY_BUILD_AS_KMDOD
    #define DXGKDDI_INTERFACE_VERSION GS_DXGKDDI_IV_WIN8
  #else
    #define DXGKDDI_INTERFACE_VERSION GS_DXGKDDI_IV_VISTA
    // #define DXGKDDI_INTERFACE_VERSION GS_DXGKDDI_IV_WDDM3_0
  #endif
#endif

#ifndef D3D_FEATURE_LEVEL_MAJOR
  #define D3D_FEATURE_LEVEL_MAJOR 10
#endif

#ifndef D3D_FEATURE_LEVEL_MINOR
  #define D3D_FEATURE_LEVEL_MINOR 0
#endif

#ifndef D3D_11_ON_10
  #define D3D_11_ON_10 0
#endif

#ifndef ENFORCE_VAGUE_STATUSES
  #define ENFORCE_VAGUE_STATUSES (0)
#endif

#endif
