// ReSharper disable CppClangTidyModernizeMacroToEnum
#pragma once

#ifndef HY_VENDOR_ID
  #define HY_VENDOR_ID (0xFFFD)
#endif

#ifndef HY_BUILD_AS_KMDOD
  #define HY_BUILD_AS_KMDOD (0)
#endif

#ifndef HY_KMDOD_ENABLE_VSYNC_INTERRUPTS
  #define HY_KMDOD_ENABLE_VSYNC_INTERRUPTS (1)
#endif

#define GS_DXGKDDI_INTERFACE_VERSION_VISTA      0x1052
#define GS_DXGKDDI_INTERFACE_VERSION_VISTA_SP1  0x1053
#define GS_DXGKDDI_INTERFACE_VERSION_WIN7       0x2005
#define GS_DXGKDDI_INTERFACE_VERSION_WIN8       0x300E
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM1_3    0x4002
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM1_3_PATH_INDEPENDENT_ROTATION  0x4003
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_0    0x5023
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_1    0x6003
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_1_5  0x6010     // Used in RS1.7 for GPU-P
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_1_6  0x6011     // Used in RS1.8 for GPU-P
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_2    0x700A
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_3    0x8001
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_4    0x9006
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_5    0xA00B
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_6    0xB004
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_7    0xC004
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_8    0xD001
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM2_9    0xE003
#define GS_DXGKDDI_INTERFACE_VERSION_WDDM3_0    0xF003

#ifndef DXGKDDI_INTERFACE_VERSION
  #if HY_BUILD_AS_KMDOD
    #define DXGKDDI_INTERFACE_VERSION GS_DXGKDDI_INTERFACE_VERSION_WIN8
  #else
    #define DXGKDDI_INTERFACE_VERSION GS_DXGKDDI_INTERFACE_VERSION_VISTA
    // #define DXGKDDI_INTERFACE_VERSION GS_DXGKDDI_INTERFACE_VERSION_WDDM3_0
  #endif
#endif